-- deactivating foreign keys to be able to delete
ALTER TABLE ProductInventory NOCHECK CONSTRAINT ALL;
ALTER TABLE OrderDetails NOCHECK CONSTRAINT ALL;
ALTER TABLE Orders NOCHECK CONSTRAINT ALL;
ALTER TABLE Expenses NOCHECK CONSTRAINT ALL;
ALTER TABLE CoffeeStores NOCHECK CONSTRAINT ALL;
ALTER TABLE Products NOCHECK CONSTRAINT ALL;
ALTER TABLE Suppliers NOCHECK CONSTRAINT ALL;
ALTER TABLE Employees NOCHECK CONSTRAINT ALL;
ALTER TABLE Customers NOCHECK CONSTRAINT ALL;
ALTER TABLE Locations NOCHECK CONSTRAINT ALL;

-- clearing the data
DELETE FROM ProductInventory;
DELETE FROM OrderDetails;
DELETE FROM Orders;
DELETE FROM Expenses;
DELETE FROM Products;
DELETE FROM Suppliers;
DELETE FROM CoffeeStores;
DELETE FROM Employees;
DELETE FROM Customers;
DELETE FROM Locations;

-- reactivating foreign keys
ALTER TABLE ProductInventory CHECK CONSTRAINT ALL;
ALTER TABLE OrderDetails CHECK CONSTRAINT ALL;
ALTER TABLE Orders CHECK CONSTRAINT ALL;
ALTER TABLE Expenses CHECK CONSTRAINT ALL;
ALTER TABLE CoffeeStores CHECK CONSTRAINT ALL;
ALTER TABLE Products CHECK CONSTRAINT ALL;
ALTER TABLE Suppliers CHECK CONSTRAINT ALL;
ALTER TABLE Employees CHECK CONSTRAINT ALL;
ALTER TABLE Customers CHECK CONSTRAINT ALL;
ALTER TABLE Locations CHECK CONSTRAINT ALL;
